# Generated by Django 2.2.28 on 2024-06-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_users', '0002_follow_followrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
